# yamllint disable rule:line-length
---
sudo: required
language: rust

git:
  submodules: false

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++
    - os: osx
      osx_image: xcode8
      env: CC=clang CXX=clang++
    - os: windows
      env: CC=clang CXX=clang++

cache: cargo

script:
  - ./.travis.sh

_github_api_key: &_github_api_key
  api_key:
    secure: "Qy4OGA9URnKapw7+krvgVTTwHPN611F6nGJHN+n58/JC6V6OabNSSgCvSXq49sl60IrbwzbJXCzSmMUJLXEcSKt3s+O1UABv0ehtWy6EDxB7UmLc+mAIxkIAK2QNOJVnHFiRa9EiQOCcoQwHQPmNUtDdn4fHu7dY61WsJ3u/DvokK0Af+ptVK7WYhPeFceknotRf/4yh7AVvJQ7z/v0PDpmbNvcp1DvUR12N/PJJZXZbVPwlL7TCHtMAWvGLPafwVupXM9PnqGpRvgER91BsejGS1eFYasrygREXswdGsK25ECe+nr4X3kAAFhajgb3sqAE8jlMeGxQfYZS7KW4ecYZHoHXVsZ+gbG5Yp+S2S0pDRKPTGIXkFdmurxIhHxA+/vDuHZHBclM3q+sykEkcyBaPqZ1keNYhiTBVlPrZes6mbmmD9WRrKYAfjY4sgcp19/F0Ru/RMf8tOVMzGYqgwlyigXpxGz0sEb6TQyVVA43PxVfB8jL4mTGUvwR0VQKh86HcwQA+uPDCIQjLNpSaeOpxHByc0JofD1AOPbypaw9CL7OqQQBz3CeYwWtBdwy4mg09mRTay0r+9JPEcMD8Bu6ofbAcSIKgFNStBnpeJUChO57F1SA/dkrMc6tmdas1I0IzHBJ5d0LEap7t3hFPNEreuuiB64ZiTkXWkztfnNg="

deploy:
  - provider: releases
    file_glob: true
    file: "yamloboros-*windows*.zip"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = windows"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "yamloboros-*darwin*.tar.gz"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "yamloboros-*linux*.tar.gz"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
    <<: *_github_api_key
...
